# Generated by Django 4.2.4 on 2023-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newscls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('nevisande', models.CharField(max_length=40)),
            ],
        ),
    ]
